// Package commit handles clone/fetch/commit/push/PR operations.
package commit

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// Mode is the per-repo push mode.
type Mode string

const (
	ModePR         Mode = "pr"
	ModeDirect     Mode = "direct"
	ModeCommitOnly Mode = "commit-only"
	ModeSkip       Mode = "skip"
)

const PRBody = "Generated by gh-readme-pipeline."


// Result is the outcome of CommitAndPush.
type Result struct {
	Status string // "pushed" | "pr_opened" | "commit_only" | "skipped" | "failed"
	Mode   string
	PRURL  string
	Error  string
}

// Options for CommitAndPush.
type Options struct {
	Mode                  Mode
	HadReadmeBefore       bool
	DryRun                bool
	SkipCI                bool
	CommitMessageOverride string // empty → use default "docs: <verb> README"
}

// BuildCommitMessage applies verb selection + skip-ci suffix + override.
func BuildCommitMessage(opts Options) string {
	if opts.CommitMessageOverride != "" {
		msg := opts.CommitMessageOverride
		if opts.SkipCI {
			msg += " [skip ci]"
		}
		return msg
	}
	verb := "add"
	if opts.HadReadmeBefore {
		verb = "update"
	}
	msg := "docs: " + verb + " README"
	if opts.SkipCI {
		msg += " [skip ci]"
	}
	return msg
}

// BranchName returns docs/readme-pipeline-<unix>.
func BranchName(now time.Time) string {
	return fmt.Sprintf("docs/readme-pipeline-%d", now.Unix())
}

// Clone runs `git clone --depth=1 --filter=blob:none <ssh> <dir>`.
func Clone(ctx context.Context, sshURL, dir string) error {
	cmd := exec.CommandContext(ctx, "git", "clone", "--depth=1", "--filter=blob:none", sshURL, dir)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("git clone: %w: %s", err, out)
	}
	return nil
}

// Fetch refreshes an existing shallow clone.
func Fetch(ctx context.Context, dir string) error {
	cmd := exec.CommandContext(ctx, "git", "fetch", "--depth=1")
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("git fetch: %w: %s", err, out)
	}
	return nil
}

// WarnGPGSigning prints a warning to stderr if commit.gpgsign=true but no key.
func WarnGPGSigning(ctx context.Context, dir string, stderr io.Writer) {
	on := strings.TrimSpace(getConfig(ctx, dir, "commit.gpgsign"))
	if on != "true" {
		return
	}
	key := strings.TrimSpace(getConfig(ctx, dir, "user.signingkey"))
	if key == "" {
		fmt.Fprintln(stderr, "WARNING: GPG signing is enabled but no signingkey configured; commits may fail.")
	}
}

func getConfig(ctx context.Context, dir, key string) string {
	cmd := exec.CommandContext(ctx, "git", "config", key)
	cmd.Dir = dir
	out, _ := cmd.Output()
	return string(out)
}

// CommitAndPush performs the requested mode operations against repoDir.
func CommitAndPush(ctx context.Context, repoDir string, opts Options) Result {
	if strings.ContainsAny(opts.CommitMessageOverride, "\r\n") {
		return Result{Status: "failed", Mode: string(opts.Mode), Error: "commit_message must be single line"}
	}
	if opts.Mode == ModeSkip || opts.Mode == "" {
		return Result{Status: "skipped"}
	}
	msg := BuildCommitMessage(opts)
	switch opts.Mode {
	case ModePR:
		return runPR(ctx, repoDir, msg, opts.DryRun)
	case ModeDirect:
		return runDirect(ctx, repoDir, msg, opts.DryRun)
	case ModeCommitOnly:
		return runCommitOnly(ctx, repoDir, msg)
	}
	return Result{Status: "failed", Mode: string(opts.Mode), Error: "unknown mode"}
}

func runPR(ctx context.Context, dir, msg string, dryRun bool) Result {
	branch := BranchName(time.Now())
	for _, args := range [][]string{
		{"checkout", "-b", branch},
		{"add", "README.md"},
		{"commit", "-m", msg},
	} {
		if err := runGit(ctx, dir, args...); err != nil {
			return Result{Status: "failed", Mode: "pr", Error: err.Error()}
		}
	}
	if dryRun {
		return Result{Status: "pr_opened", Mode: "pr"}
	}
	if err := runGit(ctx, dir, "push", "-u", "origin", branch); err != nil {
		return Result{Status: "failed", Mode: "pr", Error: err.Error()}
	}
	out, code, err := runOut(ctx, dir, "gh", "pr", "create", "--title", msg, "--body", PRBody)
	if err != nil {
		return Result{Status: "failed", Mode: "pr", Error: err.Error()}
	}
	if code != 0 {
		return Result{Status: "failed", Mode: "pr", Error: fmt.Sprintf("gh pr create failed (exit=%d): %s", code, strings.TrimSpace(out))}
	}
	return Result{Status: "pr_opened", Mode: "pr", PRURL: strings.TrimSpace(out)}
}

func runDirect(ctx context.Context, dir, msg string, dryRun bool) Result {
	for _, args := range [][]string{
		{"add", "README.md"},
		{"commit", "-m", msg},
	} {
		if err := runGit(ctx, dir, args...); err != nil {
			return Result{Status: "failed", Mode: "direct", Error: err.Error()}
		}
	}
	if dryRun {
		return Result{Status: "pushed", Mode: "direct"}
	}
	if err := runGit(ctx, dir, "push", "origin", "HEAD"); err != nil {
		return Result{Status: "failed", Mode: "direct", Error: err.Error()}
	}
	return Result{Status: "pushed", Mode: "direct"}
}

func runCommitOnly(ctx context.Context, dir, msg string) Result {
	for _, args := range [][]string{
		{"add", "README.md"},
		{"commit", "-m", msg},
	} {
		if err := runGit(ctx, dir, args...); err != nil {
			return Result{Status: "failed", Mode: "commit-only", Error: err.Error()}
		}
	}
	return Result{Status: "commit_only", Mode: "commit-only"}
}

func runGit(ctx context.Context, dir string, args ...string) error {
	cmd := exec.CommandContext(ctx, "git", args[0:]...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("git %s: %w: %s", args[0], err, out)
	}
	return nil
}

func runOut(ctx context.Context, dir, name string, args ...string) (string, int, error) {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	code := 0
	var ee *exec.ExitError
	if errors.As(err, &ee) {
		code = ee.ExitCode()
		err = nil
	}
	return string(out), code, err
}

// EnsureReposDir creates reposDir if missing.
func EnsureReposDir(reposDir string) error {
	return os.MkdirAll(reposDir, 0o755)
}

// CloneOrFetch clones if missing, otherwise fetches.
func CloneOrFetch(ctx context.Context, sshURL, repoDir string) error {
	if _, err := os.Stat(filepath.Join(repoDir, ".git")); err == nil {
		return Fetch(ctx, repoDir)
	}
	return Clone(ctx, sshURL, repoDir)
}
